export const dataUsers = [
  {
    id: 1,
    userName: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "0901234567",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    userName: "Trần Thị B",
    email: "tranthib@example.com",
    phone: "0912345678",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    userName: "Lê Văn C",
    email: "levanc@example.com",
    phone: "0923456789",
    role: "Manager",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    userName: "Phạm Thị D",
    email: "phamthid@example.com",
    phone: "0934567890",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    userName: "Hoàng Văn E",
    email: "hoangvane@example.com",
    phone: "0945678901",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    userName: "Ngô Thị F",
    email: "ngothif@example.com",
    phone: "0956789012",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    userName: "Đặng Văn G",
    email: "dangvang@example.com",
    phone: "0967890123",
    role: "Manager",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    userName: "Vũ Thị H",
    email: "vuthih@example.com",
    phone: "0978901234",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    userName: "Bùi Văn I",
    email: "buivani@example.com",
    phone: "0989012345",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    userName: "Đỗ Thị K",
    email: "dothik@example.com",
    phone: "0990123456",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    userName: "Hồ Văn L",
    email: "hovanl@example.com",
    phone: "0901234567",
    role: "Manager",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    userName: "Lý Thị M",
    email: "lythim@example.com",
    phone: "0912345678",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    userName: "Phan Văn N",
    email: "phanvann@example.com",
    phone: "0923456789",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    userName: "Mai Thị P",
    email: "maithip@example.com",
    phone: "0934567890",
    role: "User",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    userName: "Trịnh Văn Q",
    email: "trinhvanq@example.com",
    phone: "0945678901",
    role: "Manager",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];
